version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["./export.sh", "-v", "./config.xml"]  

  redis:
    image: redis
    ports:
      - "6380:6379"  

